### ISSUE TITLE
meta data annotation layer does not match with the annotation layer in annis

### ISSUE THREAD

**Issue by VivianV** [korpling/pepperModules-SaltInfoModules#45]
The meta annotations in annis are introduced by a "meta::" namespace, if the annotation layer contains any doubled colons (e.g.: "X::sex"), they will be realized by a single colon preceded by the "meta::"-namespace (e.g.: "meta::X:sex"). One can not search for the original "X::sex"-annotation in annis, thus it's maybe desirable to rename those meta annotations in the described way.

**Comment by FlorianZipser** [comment]
Indeed that's a problem. But this cannot be resolved at this point in the pipeline. The renaming must happen before the export phase, maybe in a kind of a "renamer module" which could rename annotations by a customized mapping table.  Since the SaltInfoExporter and the ANNISExporter are just exporters, they are one the same level and don't know each other. Thus it is not assumable for one of them what the other one does, or more precisely the SaltInfoModuleExporter does not know about the renaming solutions of the ANNISExporter.

**Comment by VivianV** [comment]
But maybe we could change this in the html-visualization, since the html page provides an overview of all annotation layers for potential users? (this would of course cause a mismatch between xml and html contents

**Comment by FlorianZipser** [comment]
I am not sure whether I got you're point. I think the only thing we can do here is to remove the link to Annis for that kind of names or values.

**Comment by VivianV** [comment]
While producing the html with xslt, we could check, whether the annotation is a meta annotation, set the namespace "meta" in front of the annotation layer, check for doubled colons and replace those with a single one, so that the visualization of those meta annotations matches its representation in annis.
